services:
  django:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/www/app/staticfiles
      - media_volume:/home/www/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/www/app/staticfiles
      - media_volume:/home/www/app/media
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
