# Generated by Django 5.1.1 on 2024-10-13 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AddField(
            model_name='student',
            name='came_from',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Откуда перевелся'),
        ),
        migrations.CreateModel(
            name='RupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rup_files', to='rup.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Файл РУП',
                'verbose_name_plural': 'Файлы РУПов',
                'ordering': ['-id'],
            },
        ),
    ]
