# Generated by Django 5.1.1 on 2024-12-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыт'),
        ),
    ]
