# Generated by Django 5.1.1 on 2024-12-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0005_remove_botphrase_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
