# Generated by Django 5.1.1 on 2024-12-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0006_alter_meeting_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rupfile',
            name='tg_file_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ID файла в telegram'),
        ),
        migrations.AlterField(
            model_name='rupentry',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rup_entries', to='rup.department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='student',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
