FROM python:3.11-alpine AS builder

ENV APP_DIR=/usr/src/app

WORKDIR $APP_DIR

RUN apk update && \
    apk add --no-cache \
    gcc postgresql-dev python3-dev musl-dev

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip wheel --no-cache-dir --no-deps --wheel-dir $APP_DIR/wheels -r requirements.txt


FROM python:3.11-alpine

ENV APP_DIR=/usr/src/app
ENV PYTHONUNBUFFERED 1

WORKDIR $APP_DIR

RUN apk add --no-cache postgresql-libs

COPY --from=builder $APP_DIR/wheels /wheels
COPY --from=builder $APP_DIR/requirements.txt .
RUN pip install --no-cache /wheels/*

COPY ./entrypoint.sh .
RUN sed -i "s/\r$//g" $APP_DIR/entrypoint.sh && \
    chmod +x $APP_DIR/entrypoint.sh

COPY . .

ENTRYPOINT $APP_DIR/entrypoint.sh
